---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Introduction to R
================

### Moffitt Cancer Center 

-----

:calendar: Wednesday June X - July X, 2022

:alarm_clock: 3-4 pm

:office: via Zoom (link coming soon)

:computer: [Moffitt](https://moffitt.org/)

-----

## Setup

The course will be hosted through ....

<!-- 
* When you're done, put a green post-it on your computer. 
* If you need help, put up a pink post-it.
-->

## Slides

<!--
* Rewrite as links to slides on github once they are made
* [Name of talk](path/to/slides.pdf)
-->



## Questions?

Feel free to ask questions in the [GitHub Issues](https://github.com).

## Overview

This is a X week course designed to introduce future users to R and Rstudio.
We will cover data cleaning using the `tidyverse`, creating visuals with `ggplot`,
basic statistical analysis and writing documents with `Rmarkdown`. In the end 
you should be able to: 

<!--
Each instructor should provide a one sentence summary of what participants
will be able to do after thier lecture 
-->

* import and manipulate data into different formats
* create new variables and recode existing ones 
* plot data using the appropriate figure type 
* perform basic statistics
* write Rmarkdown reports

## Who is this course designed for?

Have you never written any code in R or any other programming language? Are you
familiar with R, but hoping to bulk up your basic skills? Have you used R but are
new to the `tidyverse` framework? 

## Learning objectives

Introduction to R/Rstudio

  - Get familiar with the R and Rstudio environment
  - Understand basic R code structure (packages, data structures)
    
Data import and manipulation - Part I

  - Import various data types 
  - Explain the fundamentals of "tidy data" and the `tidyverse`
  - Clean data sets using `dplyr` verbs
    
Data manipulation and cleaning - Part II

  - Merge data sets
  - Transform data  
    
Visualization 

Basic statistics 

## Materials

Materials will be made available on [GitHub](https://github.com/FridleyLab/Intro_to_R_2022/).  
If you are using an organization-issued laptop, you may want to verify before you arrive that you can access GitHub.

## Schedule and Links

*   June XX - Basics of R/RStudio
*   June XX - Data import and wrangling part I
*   June XX - Data import and wrangling part II
*   June XX - Visualizations with `ggplot2`
*   July XX - Basic statistics
*   July XX - `rmarkdown`

## Instructors

<!--
Add links to personal websites and double check personal info
* add small blurbs/pictures for each instructor? 
-->

This course is taught by members of Moffitt staff including Jordan
Creed, a data scientist in the Department of Health Informatics, Zachary
Thompson and Ram Thappa, biostatisticians in the Bioinformatics and
Biostatistics Core.

-----